### ISSUE TITLE
Kubeadm init --dry-run doestn't work if using an external ca

### ISSUE THREAD

**Issue by Haleygo** [kubernetes/kubeadm#2512]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:17:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
- **OS** (e.g. from /etc/os-release): CentOS 7.6

## What happened?
When I run kubeadm init --dry-run, if I have cert files under /etc/kubernetes/pki (kubeadm default certificates directory), it will exit with error: "couldn't load the certificate file /etc/kubernetes/tmp/kubeadm-init-dryrun990455224/ca.crt"

> [root@10-6-150-100 ~]# ls /etc/kubernetes/
manifests  pki  pki-bak  tmp
[root@10-6-150-100 ~]# ls /etc/kubernetes/pki
apiserver.crt              apiserver.key                 ca.crt  front-proxy-ca.crt      front-proxy-client.key
apiserver-etcd-client.crt  apiserver-kubelet-client.crt  ca.key  front-proxy-ca.key      sa.key
apiserver-etcd-client.key  apiserver-kubelet-client.key  etcd    front-proxy-client.crt  sa.pub
[root@10-6-150-100 ~]# kubeadm init --dry-run --v=5
I0621 22:40:11.757805   22401 initconfiguration.go:115] detected and using CRI socket: /var/run/dockershim.sock
I0621 22:40:11.758699   22401 interface.go:431] Looking for default routes with IPv4 addresses
I0621 22:40:11.758721   22401 interface.go:436] Default route transits interface "ens192"
I0621 22:40:11.760800   22401 interface.go:208] Interface ens192 is up
I0621 22:40:11.760900   22401 interface.go:256] Interface "ens192" has 3 addresses :[10.6.150.100/16 fa01:150::100/64 fe80::d922:ee70:d7cf:3f6d/64].
I0621 22:40:11.760946   22401 interface.go:223] Checking addr  10.6.150.100/16.
I0621 22:40:11.760957   22401 interface.go:230] IP found 10.6.150.100
I0621 22:40:11.760970   22401 interface.go:262] Found valid IPv4 address 10.6.150.100 for interface "ens192".
I0621 22:40:11.760981   22401 interface.go:442] Found active IP 10.6.150.100
I0621 22:40:11.928552   22401 version.go:185] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I0621 22:40:12.947297   22401 certs.go:487] validating certificate period for CA certificate
I0621 22:40:12.947478   22401 certs.go:487] validating certificate period for front-proxy CA certificate
[init] Using Kubernetes version: v1.21.2
[preflight] Running pre-flight checks
I0621 22:40:12.947731   22401 checks.go:582] validating Kubernetes and kubeadm version
I0621 22:40:12.947780   22401 checks.go:167] validating if the firewall is enabled and active
	[WARNING Firewalld]: firewalld is active, please ensure ports [6443 10250] are open or your cluster may not function correctly
I0621 22:40:12.967761   22401 checks.go:202] validating availability of port 6443
I0621 22:40:12.968333   22401 checks.go:202] validating availability of port 10259
I0621 22:40:12.968392   22401 checks.go:202] validating availability of port 10257
I0621 22:40:12.968451   22401 checks.go:287] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0621 22:40:12.968470   22401 checks.go:287] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0621 22:40:12.968479   22401 checks.go:287] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0621 22:40:12.968489   22401 checks.go:287] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0621 22:40:12.968502   22401 checks.go:437] validating if the connectivity type is via proxy or direct
I0621 22:40:12.968550   22401 checks.go:476] validating http connectivity to first IP address in the CIDR
I0621 22:40:12.968590   22401 checks.go:476] validating http connectivity to first IP address in the CIDR
I0621 22:40:12.968600   22401 checks.go:103] validating the container runtime
I0621 22:40:13.143913   22401 checks.go:129] validating if the "docker" service is enabled and active
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
I0621 22:40:13.340326   22401 checks.go:336] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0621 22:40:13.340402   22401 checks.go:336] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0621 22:40:13.340442   22401 checks.go:654] validating whether swap is enabled or not
I0621 22:40:13.340851   22401 checks.go:377] validating the presence of executable conntrack
I0621 22:40:13.341151   22401 checks.go:377] validating the presence of executable ip
I0621 22:40:13.341390   22401 checks.go:377] validating the presence of executable iptables
I0621 22:40:13.341421   22401 checks.go:377] validating the presence of executable mount
I0621 22:40:13.341605   22401 checks.go:377] validating the presence of executable nsenter
I0621 22:40:13.341968   22401 checks.go:377] validating the presence of executable ebtables
I0621 22:40:13.341996   22401 checks.go:377] validating the presence of executable ethtool
I0621 22:40:13.342015   22401 checks.go:377] validating the presence of executable socat
I0621 22:40:13.342043   22401 checks.go:377] validating the presence of executable tc
I0621 22:40:13.342061   22401 checks.go:377] validating the presence of executable touch
I0621 22:40:13.342083   22401 checks.go:525] running all checks
I0621 22:40:13.544313   22401 checks.go:408] checking whether the given node name is valid and reachable using net.LookupHost
	[WARNING Hostname]: hostname "10-6-150-100" could not be reached
	[WARNING Hostname]: hostname "10-6-150-100": lookup 10-6-150-100 on 223.5.5.5:53: no such host
I0621 22:40:13.558142   22401 checks.go:623] validating kubelet version
I0621 22:40:13.707185   22401 checks.go:129] validating if the "kubelet" service is enabled and active
I0621 22:40:13.725396   22401 checks.go:202] validating availability of port 10250
I0621 22:40:13.726073   22401 checks.go:202] validating availability of port 2379
I0621 22:40:13.726141   22401 checks.go:202] validating availability of port 2380
I0621 22:40:13.726221   22401 checks.go:250] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Would pull the required images (like 'kubeadm config images pull')
[certs] Using certificateDir folder "/etc/kubernetes/tmp/kubeadm-init-dryrun990455224"
I0621 22:40:13.726481   22401 certs.go:487] validating certificate period for ca certificate
[certs] Using existing ca certificate authority
I0621 22:40:13.726835   22401 certs.go:487] validating certificate period for apiserver certificate
[certs] Using existing apiserver certificate and key on disk
I0621 22:40:13.727216   22401 certs.go:487] validating certificate period for apiserver-kubelet-client certificate
[certs] Using existing apiserver-kubelet-client certificate and key on disk
I0621 22:40:13.727528   22401 certs.go:487] validating certificate period for front-proxy-ca certificate
[certs] Using existing front-proxy-ca certificate authority
I0621 22:40:13.727774   22401 certs.go:487] validating certificate period for front-proxy-client certificate
[certs] Using existing front-proxy-client certificate and key on disk
I0621 22:40:13.728144   22401 certs.go:487] validating certificate period for etcd/ca certificate
[certs] Using existing etcd/ca certificate authority
I0621 22:40:13.728379   22401 certs.go:487] validating certificate period for etcd/server certificate
[certs] Using existing etcd/server certificate and key on disk
I0621 22:40:13.728750   22401 certs.go:487] validating certificate period for etcd/peer certificate
[certs] Using existing etcd/peer certificate and key on disk
I0621 22:40:13.729070   22401 certs.go:487] validating certificate period for etcd/healthcheck-client certificate
[certs] Using existing etcd/healthcheck-client certificate and key on disk
I0621 22:40:13.729403   22401 certs.go:487] validating certificate period for apiserver-etcd-client certificate
[certs] Using existing apiserver-etcd-client certificate and key on disk
I0621 22:40:13.729604   22401 certs.go:76] creating new public/private key files for signing service account users
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes/tmp/kubeadm-init-dryrun990455224"
I0621 22:40:14.197025   22401 kubeconfig.go:101] creating kubeconfig file for admin.conf
open /etc/kubernetes/tmp/kubeadm-init-dryrun990455224/ca.crt: no such file or directory
couldn't load the certificate file /etc/kubernetes/tmp/kubeadm-init-dryrun990455224/ca.crt
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadCertFromDisk
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:289
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadCertAndKeyFromDisk
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:270
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.getKubeConfigSpecs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:140
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFiles
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:110
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.CreateKubeConfigFile
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:102
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runKubeConfigFile.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/kubeconfig.go:144
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:152
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
failed to load certificate
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadCertAndKeyFromDisk
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:272
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.getKubeConfigSpecs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:140
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFiles
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:110
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.CreateKubeConfigFile
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:102
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runKubeConfigFile.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/kubeconfig.go:144
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:152
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
couldn't create a kubeconfig; the CA files couldn't be loaded
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.getKubeConfigSpecs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:142
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFiles
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:110
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.CreateKubeConfigFile
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:102
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runKubeConfigFile.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/kubeconfig.go:144
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:152
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
error execution phase kubeconfig/admin
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:152
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371

## What you expected to happen?
Kubeadm init dry-run works normally when certs already exist in /etc/kubernetes/pki, just ignore them and create new certs in tmp kubeadm-init-dryrun directory.

## How to reproduce it (as minimally and precisely as possible)?
1. run kubeadm init to initialize your kubernetes control-plane successfully. 
2. mv /etc/kubernetes/pki somewhere else and run kubeadm reset
3. mv pki back and run kubeadm init --dry-run

It can be reproduced when /etc/kubernetes/pki only have ca.crt or apiserver.crt or any other cert (cert need to be correct) too. 

Kubeadm init has similar error when there is ca.crt under /etc/kubernetes/pki, but I think it is acceptable cause it remind me to check my environment, maybe need to check cert file completeness in preflight and give a more friendly error message or tip?

> [root@10-6-150-100 ~]# ls /etc/kubernetes/
manifests  pki  pki-bak  tmp
[root@10-6-150-100 ~]# ls /etc/kubernetes/pki
ca.crt
[root@10-6-150-100 ~]# kubeadm init --v=5 --image-repository=registry.aliyuncs.com/google_containers --ignore-preflight-errors=all
I0621 22:26:46.368210   15768 initconfiguration.go:115] detected and using CRI socket: /var/run/dockershim.sock
I0621 22:26:46.368590   15768 interface.go:431] Looking for default routes with IPv4 addresses
I0621 22:26:46.368603   15768 interface.go:436] Default route transits interface "ens192"
I0621 22:26:46.368899   15768 interface.go:208] Interface ens192 is up
I0621 22:26:46.368983   15768 interface.go:256] Interface "ens192" has 3 addresses :[10.6.150.100/16 fa01:150::100/64 fe80::d922:ee70:d7cf:3f6d/64].
I0621 22:26:46.369020   15768 interface.go:223] Checking addr  10.6.150.100/16.
I0621 22:26:46.369031   15768 interface.go:230] IP found 10.6.150.100
I0621 22:26:46.369045   15768 interface.go:262] Found valid IPv4 address 10.6.150.100 for interface "ens192".
I0621 22:26:46.369057   15768 interface.go:442] Found active IP 10.6.150.100
I0621 22:26:46.543857   15768 version.go:185] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I0621 22:26:47.531745   15768 certs.go:487] validating certificate period for CA certificate
I0621 22:26:47.531896   15768 certs.go:487] validating certificate period for API server certificate
open /etc/kubernetes/pki/apiserver.key: no such file or directory
couldn't load the private key file /etc/kubernetes/pki/apiserver.key
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadKeyFromDisk
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:321
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.validateSignedCertWithCA
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:429
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.validateSignedCert
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:422
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.UsingExternalCA
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:348
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:380
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func3
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:196
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:144
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
failure loading key for apiserver
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.validateSignedCertWithCA
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:431
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.validateSignedCert
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:422
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.UsingExternalCA
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:348
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:380
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func3
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:196
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:144
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
invalid or incomplete external CA
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:385
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func3
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:196
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:144
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371

**Comment by Haleygo** [comment]
/assign
I will pull a request to fix the error in dry-run, but I am not sure about the error in kubeadm init, should we just leave it?

**Comment by neolit123** [comment]
thanks for logging the issue.
this does seem like a bug.

basically --dru-run should work regardless on state on disk for both init/join/upgrade.

/kind bug
/priority backlog
/milestone v1.22

**Comment by Haleygo** [comment]
@neolit123 Hi, I went to check the whole process, and here is my understanding:
I used to think that dry-run should work under any circumstance, but now I find out that there is an exception: intentionally set some ca files on host to check whether an external ca available. In that case, dry-run can be failed and report those files is not right. And that's the error I reported above.
So this changes the problem that I need to fix, make sure that if a right external ca is provided, dry-run can work too. And I pull a request for this.
Do you see any misunderstanding or have any comments, thanks :)

**Comment by neolit123** [comment]
it is a bit tricky.

kubeadm supports certificates signed by an external CA.
which means that if files exist in the pki folder, kubeadm validates them and uses them.

if the user has certs in the folder and runs with --dry-run, we can assume that they want to dry-run using these certs on disk.
they actually want to test using these certs on disk.

so i think dry-run should use them.

> open /etc/kubernetes/pki/apiserver.key: no such file or directory
couldn't load the private key file /etc/kubernetes/pki/apiserver.key

the errors that i see above is because there are missing .key files.
when the user is using an external CA they must prepare both cert and key files and put them in the pki folder manually.

if the key files are really missing, then dry-run is expected to file i think!

**Comment by Haleygo** [comment]
Yes.
> if the key files are really missing, then dry-run is expected to fail too, in my option.

So I fixed the problem, now if provide a right external ca , dry-run can work too.
It used to fail even if I put all the files that needed in the right place because it check the wrong place [in the begainning](https://github.com/kubernetes/kubernetes/blob/07358f166321f435ea71256ae3fe0a35e2ae5916/cmd/kubeadm/app/cmd/init.go#L389):
![image](https://user-images.githubusercontent.com/39937150/123456654-ac66af00-d615-11eb-8808-4986fb29a06f.png)
And the logs are like this:

> [root@10-6-150-51 kubernetes]# ls /etc/kubernetes
admin.conf  controller-manager.conf  kubeadm  kubeadm-config.yaml  kubelet.conf  manifests  pki  scheduler.conf  tmp
[root@10-6-150-51 kubernetes]# ls /etc/kubernetes/pki/
apiserver.crt              apiserver-etcd-client.key  apiserver-kubelet-client.crt  ca.crt      etcd                front-proxy-ca.key      front-proxy-client.key  sa.pub
apiserver-etcd-client.crt  apiserver.key              apiserver-kubelet-client.key  ca.key-bak  front-proxy-ca.crt  front-proxy-client.crt  sa.key
[root@10-6-150-51 kubernetes]# kubeadm init --dry-run --v=5
I0626 00:13:59.433184   10186 initconfiguration.go:115] detected and using CRI socket: /var/run/dockershim.sock
I0626 00:13:59.433466   10186 interface.go:431] Looking for default routes with IPv4 addresses
I0626 00:13:59.433495   10186 interface.go:436] Default route transits interface "ens192"
I0626 00:13:59.433744   10186 interface.go:208] Interface ens192 is up
I0626 00:13:59.433848   10186 interface.go:256] Interface "ens192" has 4 addresses :[10.6.150.51/16 10.6.151.120/32 fe80::3b8a:fef7:3411:aca2/64 fe80::13a3:2ef:5d1b:22b2/64].
I0626 00:13:59.433885   10186 interface.go:223] Checking addr  10.6.150.51/16.
I0626 00:13:59.433894   10186 interface.go:230] IP found 10.6.150.51
I0626 00:13:59.433905   10186 interface.go:262] Found valid IPv4 address 10.6.150.51 for interface "ens192".
I0626 00:13:59.433914   10186 interface.go:442] Found active IP 10.6.150.51
I0626 00:13:59.583809   10186 version.go:185] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
W0626 00:13:59.585082   10186 version.go:102] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get "https://dl.k8s.io/release/stable-1.txt": dial tcp: lookup dl.k8s.io on [::1]:53: read udp [::1]:39727->[::1]:53: read: connection refused
W0626 00:13:59.585126   10186 version.go:103] falling back to the local client version: v1.21.1
I0626 00:13:59.585713   10186 certs.go:487] validating certificate period for CA certificate
I0626 00:13:59.585829   10186 certs.go:487] validating certificate period for API server certificate
I0626 00:13:59.586327   10186 certs.go:487] validating certificate period for API server kubelet client certificate
I0626 00:13:59.586828   10186 certs.go:487] validating certificate period for ca certificate
stat /etc/kubernetes/tmp/kubeadm-init-dryrun267397107/controller-manager.conf: no such file or directory
the controller-manager.conf file does not exists or it is not valid
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.ValidateKubeconfigsForExternalCA
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:382
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:394
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func3
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:196
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:144
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371

And after fix, it's working now
> 

> W0626 00:21:22.448734   10466 kubeconfig.go:248] a kubeconfig file "/etc/kubernetes/admin.conf" exists already but has an unexpected API Server URL: expected: https://10.6.150.51:6443, got: https://10.6.151.120:6443
> W0626 00:21:22.449566   10466 kubeconfig.go:248] a kubeconfig file "/etc/kubernetes/kubelet.conf" exists already but has an unexpected API Server URL: expected: https://10.6.150.51:6443, got: https://10.6.151.120:6443
> [dryrun] Copy external ca file from /etc/kubernetes/pki/ca.crt to /etc/kubernetes/tmp/kubeadm-init-dryrun496318827/ca.crt
> [dryrun] Copy external ca file from /etc/kubernetes/admin.conf to /etc/kubernetes/tmp/kubeadm-init-dryrun496318827/admin.conf
> [dryrun] Copy external ca file from /etc/kubernetes/kubelet.conf to /etc/kubernetes/tmp/kubeadm-init-dryrun496318827/kubelet.conf
> [dryrun] Copy external ca file from /etc/kubernetes/controller-manager.conf to /etc/kubernetes/tmp/kubeadm-init-dryrun496318827/controller-manager.conf
> [dryrun] Copy external ca file from /etc/kubernetes/scheduler.conf to /etc/kubernetes/tmp/kubeadm-init-dryrun496318827/scheduler.conf
> [init] Using Kubernetes version: 1.21.1
> [preflight] Running pre-flight checks
> 	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
> [preflight] Would pull the required images (like 'kubeadm config images pull')
> [certs] Using certificateDir folder "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827"
> [certs] Using existing ca keyless certificate authority
> [certs] Using existing apiserver certificate and key on disk
> [certs] Using existing apiserver-kubelet-client certificate and key on disk
> [certs] Using existing front-proxy-ca certificate authority
> [certs] Using existing front-proxy-client certificate and key on disk
> [certs] Using existing etcd/ca certificate authority
> [certs] Using existing etcd/server certificate and key on disk
> [certs] Using existing etcd/peer certificate and key on disk
> [certs] Using existing etcd/healthcheck-client certificate and key on disk
> [certs] Using existing apiserver-etcd-client certificate and key on disk
> [certs] Using existing sa keys
> [kubeconfig] Using kubeconfig folder "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827"
> [kubeconfig] External CA mode: Using user provided admin.conf
> [kubeconfig] External CA mode: Using user provided kubelet.conf
> [kubeconfig] External CA mode: Using user provided controller-manager.conf
> [kubeconfig] External CA mode: Using user provided scheduler.conf
> [kubelet-start] Writing kubelet environment file with flags to file "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827/kubeadm-flags.env"
> [kubelet-start] Writing kubelet configuration to file "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827/config.yaml"
> [control-plane] Using manifest folder "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827"
> [control-plane] Creating static Pod manifest for "kube-apiserver"
> [control-plane] Creating static Pod manifest for "kube-controller-manager"
> [control-plane] Creating static Pod manifest for "kube-scheduler"
> [dryrun] Would ensure that "/var/lib/etcd" directory is present
> [etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827"
> [dryrun] Wrote certificates, kubeconfig files and control plane manifests to the "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827" directory
> [dryrun] The certificates or kubeconfig files would not be printed due to their sensitive nature
> [dryrun] Please examine the "/etc/kubernetes/tmp/kubeadm-init-dryrun496318827" directory for details about what would be written
> [dryrun] Would write file "/etc/kubernetes/manifests/kube-apiserver.yaml" with content:
> 	apiVersion: v1
> 	kind: Pod
> 	...
> 	...
> 	...
> [dryrun] Would perform action GET on resource "nodes" in API group "core/v1"
> [dryrun] Resource name: "10-6-150-51"
> [dryrun] Would perform action PATCH on resource "nodes" in API group "core/v1"
> [dryrun] Resource name: "10-6-150-51"
> [dryrun] Attached patch:
> 	{"metadata":{"annotations":{"kubeadm.alpha.kubernetes.io/cri-socket":"/var/run/dockershim.sock"}}}
> [upload-certs] Skipping phase. Please see --upload-certs
> [mark-control-plane] Marking the node 10-6-150-51 as control-plane by adding the labels: [node-role.kubernetes.io/master(deprecated) node-role.kubernetes.io/control-plane node.kubernetes.io/exclude-from-external-load-balancers]
> [mark-control-plane] Marking the node 10-6-150-51 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
> [dryrun] Would perform action GET on resource "nodes" in API group "core/v1"
> [dryrun] Resource name: "10-6-150-51"
> [dryrun] Would perform action PATCH on resource "nodes" in API group "core/v1"
> [dryrun] Resource name: "10-6-150-51"
> [dryrun] Attached patch:
> 	{"metadata":{"labels":{"node-role.kubernetes.io/control-plane":"","node-role.kubernetes.io/master":"","node.kubernetes.io/exclude-from-external-load-balancers":""}},"spec":{"taints":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}]}}
> [bootstrap-token] Using token: er1488.7spjku36f6vclpef
> [bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
> [dryrun] Would perform action GET on resource "secrets" in API group "core/v1"
> [dryrun] Resource name: "bootstrap-token-er1488"
> [dryrun] Would perform action CREATE on resource "secrets" in API group "core/v1"
> [dryrun] Attached object:
> 	apiVersion: v1
> 	data:
> 	...
> 	...
> 	...
> dryrun] Would perform action CREATE on resource "rolebindings" in API group "rbac.authorization.k8s.io/v1"
> [dryrun] Attached object:
> 	apiVersion: rbac.authorization.k8s.io/v1
> 	kind: RoleBinding
> 	metadata:
> 	  creationTimestamp: null
> 	  name: kube-proxy
> 	  namespace: kube-system
> 	roleRef:
> 	  apiGroup: rbac.authorization.k8s.io
> 	  kind: Role
> 	  name: kube-proxy
> 	subjects:
> 	- kind: Group
> 	  name: system:bootstrappers:kubeadm:default-node-token
> [addons] Applied essential addon: kube-proxy
> 
> Your Kubernetes control-plane has initialized successfully!
> 
> To start using your cluster, you need to run the following as a regular user:
> 
>   mkdir -p $HOME/.kube
>   sudo cp -i /etc/kubernetes/tmp/kubeadm-init-dryrun496318827/admin.conf $HOME/.kube/config
>   sudo chown $(id -u):$(id -g) $HOME/.kube/config
> 
> Alternatively, if you are the root user, you can run:
> 
>   export KUBECONFIG=/etc/kubernetes/admin.conf
> 
> You should now deploy a pod network to the cluster.
> Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
>   https://kubernetes.io/docs/concepts/cluster-administration/addons/
> 
> Then you can join any number of worker nodes by running the following on each as root:
> 
> kubeadm join 10.6.151.120:6443 --token er1488.7spjku36f6vclpef \
> 	--discovery-token-ca-cert-hash sha256:391a2d2a9dc1afe4a1027ee8178d9c1dcfeda0fe38640e5833a783415d125b68

**Comment by neolit123** [comment]
@Haleygo can we close this after merging this PR?
https://github.com/kubernetes/kubernetes/pull/103187

**Comment by Haleygo** [comment]
Sure thing, thanks :)

**Comment by bjornbouetsmith** [comment]
Hi,
This is still happening with the latest kubeadm from: 
https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch

I added my own custom CA+Key into /etc/kubernetes/pki - and when I did a kubeadm init --dryrun - I got almost the same error - except mine did not complain about the key, but the certificate itself.

When I finally after trying different versions of the CA, different CA's found this post - and found out that this could happen when I did dry run - then I tried without dry run - and it just worked.

So this is definately still an issue @neolit123 - I can provide logs if that helps tracking down the issue?

Or is my issue that the packages on the package repository are too old?

I am running version:

kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:24:08Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by neolit123** [comment]
@bjornbouetsmith I remember testing the fix, so maybe we broke it again in 1.23. Please provide logs with --v=5.

**Comment by bjornbouetsmith** [comment]
~~~
[bbs@kube1 ~]$ sudo kubeadm init --config ~/cluster-init.yml --dry-run --v=5
I0214 16:52:21.362485 2411078 initconfiguration.go:248] loading configuration from "/home/bbs/cluster-init.yml"
I0214 16:52:21.364054 2411078 kubelet.go:217] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
I0214 16:52:21.379149 2411078 certs.go:522] validating certificate period for CA certificate
[init] Using Kubernetes version: v1.23.0
[preflight] Running pre-flight checks
I0214 16:52:21.379410 2411078 checks.go:578] validating Kubernetes and kubeadm version
I0214 16:52:21.379436 2411078 checks.go:171] validating if the firewall is enabled and active
I0214 16:52:21.395698 2411078 checks.go:206] validating availability of port 6443
I0214 16:52:21.396511 2411078 checks.go:206] validating availability of port 10259
I0214 16:52:21.396582 2411078 checks.go:206] validating availability of port 10257
I0214 16:52:21.396627 2411078 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0214 16:52:21.396660 2411078 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0214 16:52:21.396675 2411078 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0214 16:52:21.396689 2411078 checks.go:283] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0214 16:52:21.396778 2411078 checks.go:433] validating if the connectivity type is via proxy or direct
I0214 16:52:21.397071 2411078 checks.go:472] validating http connectivity to first IP address in the CIDR
I0214 16:52:21.397096 2411078 checks.go:472] validating http connectivity to first IP address in the CIDR
I0214 16:52:21.397102 2411078 checks.go:107] validating the container runtime
I0214 16:52:21.510481 2411078 checks.go:133] validating if the "docker" service is enabled and active
I0214 16:52:21.545663 2411078 checks.go:332] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0214 16:52:21.545801 2411078 checks.go:332] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0214 16:52:21.545879 2411078 checks.go:654] validating whether swap is enabled or not
I0214 16:52:21.546009 2411078 checks.go:373] validating the presence of executable conntrack
I0214 16:52:21.546071 2411078 checks.go:373] validating the presence of executable ip
I0214 16:52:21.546115 2411078 checks.go:373] validating the presence of executable iptables
I0214 16:52:21.546159 2411078 checks.go:373] validating the presence of executable mount
I0214 16:52:21.546196 2411078 checks.go:373] validating the presence of executable nsenter
I0214 16:52:21.546242 2411078 checks.go:373] validating the presence of executable ebtables
I0214 16:52:21.546269 2411078 checks.go:373] validating the presence of executable ethtool
I0214 16:52:21.546282 2411078 checks.go:373] validating the presence of executable socat
I0214 16:52:21.546297 2411078 checks.go:373] validating the presence of executable tc
        [WARNING FileExisting-tc]: tc not found in system path
I0214 16:52:21.546350 2411078 checks.go:373] validating the presence of executable touch
I0214 16:52:21.546364 2411078 checks.go:521] running all checks
I0214 16:52:21.660107 2411078 checks.go:404] checking whether the given node name is valid and reachable using net.LookupHost
I0214 16:52:21.661870 2411078 checks.go:620] validating kubelet version
I0214 16:52:21.734099 2411078 checks.go:133] validating if the "kubelet" service is enabled and active
I0214 16:52:21.758805 2411078 checks.go:206] validating availability of port 10250
I0214 16:52:21.758957 2411078 checks.go:206] validating availability of port 2379
I0214 16:52:21.759062 2411078 checks.go:206] validating availability of port 2380
I0214 16:52:21.759150 2411078 checks.go:246] validating the existence and emptiness of directory /k8s/etcd
[preflight] Would pull the required images (like 'kubeadm config images pull')
[certs] Using certificateDir folder "/etc/kubernetes/tmp/kubeadm-init-dryrun2193745490"
I0214 16:52:21.759498 2411078 certs.go:522] validating certificate period for ca certificate
[certs] Using existing ca certificate authority
couldn't load ca certificate authority from /etc/kubernetes/tmp/kubeadm-init-dryrun2193745490
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.LoadCertificateAuthority
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:170
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.CreateCertAndKeyFilesWithCA
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:158
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runCertPhase.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/certs.go:288
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:255
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1581
couldn't load CA certificate ca
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.CreateCertAndKeyFilesWithCA
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:160
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runCertPhase.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/certs.go:288
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:255
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1581
error execution phase certs/apiserver
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:255
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1581
~~~

**Comment by bjornbouetsmith** [comment]
And just to iterate - the CA works, it works when I remove the --dry-run.

Perhaps you need a "unit" test for this purpose :-) Just so you don't break it again.

**Comment by neolit123** [comment]
thanks for the logs, let's reopen the issue until the regression is confirmed.

> Perhaps you need a "unit" test for this purpose :-) Just so you don't break it again.

unit tests are not feasible for this.
see https://github.com/kubernetes/kubeadm/issues/2653

**Comment by bjornbouetsmith** [comment]
> unit tests are not feasible for this. see #2653

Surely testing that a dry-run init for creating a new cluster is possible?

I can understand its not easy to make a test for upgrading an existing cluster is hard. 

But testing that a "blank" machine - can run

kubeadm init --dry-run and not get any errors seems like "easy" - since it has no other dependencies except for kubeadm & possible kubelet?

**Comment by bjornbouetsmith** [comment]
> > Surely testing that a dry-run init for creating a new cluster is possible?
> 
> the linked issue talks about how to test dry-run for different commands.

Sorry - I think we are having mis communication :-) When I wrote "unit" tests - I meant "any test" :-) And if that is already planned, awesome.

**Comment by neolit123** [comment]
i confirmed that this is still a bug.

to reproduce it quickly:
```
# make sure the host is reset
kubeadm reset -f
# creates a CA cert/key pair in /etc/kubernetes/pki
kubeadm init phase certs ca
# test the init dry-run
# the existing CA will result in a failure
kubeadm init --dry-run
```

tested with 1.23 and 1.24 (pre), but we need to test the 1.20+ in general.

**Comment by bjornbouetsmith** [comment]
I have tested with 1.22.6 - and the problem is also there.

**Comment by Haleygo** [comment]
Sorry for the late reply. 
Those problem should be there all the time because it's not the problem fixed in above pr.
Both of you guys only put the ca.key under /etc/kubernetes/pki, but missing all the [other cert](https://github.com/kubernetes/kubernetes/blob/37a0b1a3214f490c7dc50b99451a1c69d6d84ee4/cmd/kubeadm/app/phases/certs/certlist.go#L219) like apiserver. So the local certs check failed in [here](https://github.com/kubernetes/kubernetes/blob/2078864d0834b0dd61613be581272be6e5caea5f/cmd/kubeadm/app/cmd/phases/init/certs.go#L264) and try to create cert with tmp cert dir (cause we want the new cert file created in tmp dir), but tmp dir doesn't contain original ca.crt, so it failed.
![image](https://user-images.githubusercontent.com/39937150/154647952-dd071543-2871-4e29-a9a2-621dc83c63b6.png)
![image](https://user-images.githubusercontent.com/39937150/154648314-5d11b879-6915-4f01-a554-285d5f82889d.png)

When I test my fix, I copied entire /pki which contain all the certs so I miss this bug, sorry about that:(

And here is another notice, if you put both ca.crt and ca.key under /etc/kubernetes/pki, [externalCA](https://github.com/kubernetes/kubernetes/blob/2078864d0834b0dd61613be581272be6e5caea5f/cmd/kubeadm/app/cmd/init.go#L380) will be set to false and still not use your cert like [design](https://github.com/kubernetes/kubernetes/blob/37a0b1a3214f490c7dc50b99451a1c69d6d84ee4/cmd/kubeadm/app/phases/certs/certs.go#L337).
![image](https://user-images.githubusercontent.com/39937150/154637886-cd8a3f27-b59b-4bdb-a1b8-a465ed8f7901.png)
![image](https://user-images.githubusercontent.com/39937150/154650697-f7741a4a-5f5a-4b10-8ca4-cf36a8b096c6.png)

**Comment by neolit123** [comment]
Thanks for looking at this @Haleygo 
Do you think we can copy the existing contents of /etc/kubernetes/pki to the temp dir if we are dry running?

**Comment by Haleygo** [comment]
@neolit123 With pleasure!
And to be clear, @bjornbouetsmith 's case will not success even if the problem above fixed and the ca.key file deleted(to enable externalCA ).
It will failed at the beginning when [initdata](https://github.com/kubernetes/kubernetes/blob/2078864d0834b0dd61613be581272be6e5caea5f/cmd/kubeadm/app/cmd/init.go#L322) cause there is no apiserver.key and apiserver-kubelet-client.key files.
> open /etc/kubernetes/pki/apiserver.key: no such file or directory
couldn't load the private key file /etc/kubernetes/pki/apiserver.key

![image](https://user-images.githubusercontent.com/39937150/154671478-68a2ce9e-961d-4e2f-ba1f-64a843457848.png)

**Comment by neolit123** [comment]
I think the way kubeadm works today is the following. If there is a ca.key
/ ca.crt in the folder kubeadm uses them. If the ca.key is missing kubeadm
thinks its external ca and also needs the apisever certs (etc) because
there is no way to sign them.

The problem here seems to be that during dry run kubeadm says that it will
use the existing ca.key / ca.crt, but later it just fails. That is why i
think we should copy the PKI folder contents (with the ca) to the temp
folder. In theory this should fix it. But i might be missing something.

Now for the other case, if during dry run there is no ca.key and other pre
signed certs like for apisever. Dry run should fail, becase that is how the
normal run would also fail.

**Comment by Haleygo** [comment]
@neolit123 PR is ready now :)
According to my test, it should react correct with all the scenario.

**Comment by neolit123** [comment]
Thanks @Haleygo i will have a look as soon as possible.
