### ISSUE TITLE
[kubeadm] Is FileContent--proc-sys-net-bridge-bridge-nf-call-iptables still useful?

### ISSUE THREAD

**Issue by dims** [kubernetes/kubeadm#3025]
Just ran into this kubeadm check for `/proc/sys/net/bridge/bridge-nf-call-iptables` on AL2023 and had to add it to the ignore list. Also looking through our code base, we do seem to ignore this a bit (minikube, CAPD etc). So question is, does it still serve a purpose?

https://cs.k8s.io/?q=FileContent--proc-sys-net-bridge-bridge-nf-call-iptables&i=nope&files=&excludeFiles=&repos=

thanks,
Dims

/sig cluster-lifecycle

**Comment by dims** [comment]
@neolit123 ACK. thanks for the additional research! 🙏🏾

**Comment by danwinship** [comment]
In clusters where the sysctl is needed, it's not necessarily needed just for kube-proxy. (For instance, if you're using Calico for NetworkPolicy you probably need it to be set even if you're using nftables kube-proxy mode.)

But this isn't kubeadm's problem and we should just remove the checks (and the docs @neolit123 linked to). In 2016, right after we made kube-proxy stop unconditionally setting the sysctl, there was definitely a problem where some network implementations required the sysctl to be set but weren't setting it themselves. But this should all have been resolved by 2018 or so.

**Comment by neolit123** [comment]
> In clusters where the sysctl is needed, it's not necessarily needed just for kube-proxy. (For instance, if you're using Calico for NetworkPolicy you probably need it to be set even if you're using nftables kube-proxy mode.)

that's a good point.
if we remove it from kubeadm's preflight and the CR docs, some CNI might break if they are missing it in their docs.

@caseydavenport @fasaxc we are trying to understand if CNIs that require settings like:
```
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
```
already cover this in their documentation or rely on the upstream k8s docs https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
i could not find any mentions of that in:
https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart

**Comment by neolit123** [comment]
> But this isn't kubeadm's problem and we should just remove the checks (and the docs @neolit123 linked to). In 2016, right after we made kube-proxy stop unconditionally setting the sysctl, there was definitely a problem where some network implementations required the sysctl to be set but weren't setting it themselves. But this should all have been resolved by 2018 or so.

i still see this in setup guides everywhere.
but if sig net's advice is to just remove it from kubeadm and docs, we can do it for 1.30.

my problem is that i don't want to triage additional tickets about it from new users, who need the setting for some legacy reason. removing the preflight check is safer, but not so sure about remove the mention in CR docs.

**Comment by neolit123** [comment]
ok, thanks for the additional information.
given that, we can remove the check in kubeadm for 1.30, but we can leave this ticket open if needed for more discussion.

**Comment by neolit123** [comment]
> Right, but the authors of network plugins that require bridge-nf-call-itpables to be set don't want to triage tickets from new users either, so it seems reasonable to assume that at some point in the last 8 years they would have added the single line of code to set the sysctl themselves, rather than dealing with sporadic bug reports from people who hadn't noticed the warnings in the upstream documentation.

FWIW, we just close CNI tickets from this repo and tell users to ask for support in the CNI projects or on k8s support channels.
