### ISSUE TITLE
kubeadm init (offline mode) stuck on pulling images

### ISSUE THREAD

**Issue by geostant** [kubernetes/kubeadm#742]
## Versions
v1.10.0

**kubeadm version** (use `kubeadm version`):
v1.10.0

**Environment**:
- **Kubernetes version** 1.10.0
- **Cloud provider or hardware configuration**: On premise (OFFLINE)
- **OS** (e.g. from /etc/os-release): Centos
- **Kernel** (e.g. `uname -a`): 3.10.0-514
- **Others**: Docker images are pre-loaded

## What happened?
Running the same process on the internet works flawless, however on offline mode
my kubeadm init process is stuck on pulling images.

On the /var/log/messages I can see a lots of retries to connect to 127.0.0.1:6443 while
this port doesn't exists on the system.

The following docker containers exists when running `docker ps`:
controller-mananger
etcd
4 x pause

## What you expected to happen?
To run exactly as if I were online and succeed with cluster deployment

## How to reproduce it (as minimally and precisely as possible)?
- Create a local RPM repository that have the v1.10.0 packages
- Set your Centos to work with that repository
- Download all the docker containers that v1.10.0 requires and load them to your machine
- Go offline completely
- Disable DNS resolving

**Comment by chuckha** [comment]
@geostant Would you be able to provide a list of docker images downloaded prior to going offline?

**Comment by geostant** [comment]
@chuckha 
I got a script that download the relevant images and save them to tar files before I transfer them
to an offline server.

These are the images based on installed kubectl, kubelet and kubeadm version v1.10.0:
```
k8s.gcr.io/kube-proxy-amd64                v1.10.0             bfc21aadc7d3        12 days ago         97 MB
k8s.gcr.io/kube-scheduler-amd64            v1.10.0             704ba848e69a        12 days ago         50.4 MB
k8s.gcr.io/kube-controller-manager-amd64   v1.10.0             ad86dbed1555        12 days ago         148 MB
k8s.gcr.io/kube-apiserver-amd64            v1.10.0             af20925d51a3        12 days ago         225 MB
weaveworks/weave-npc                       2.2.1               26d868a4eb75        3 weeks ago         46.6 MB
weaveworks/weave-kube                      2.2.1               86e2da7dd27b        3 weeks ago         93.8 MB
k8s.gcr.io/etcd-amd64                      3.1.12              52920ad46f5b        4 weeks ago         193 MB
k8s.gcr.io/kubernetes-dashboard-amd64      v1.8.3              0c60bcf89900        7 weeks ago         102 MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64     1.14.8              c2ce1ffb51ed        3 months ago        40.9 MB
k8s.gcr.io/k8s-dns-sidecar-amd64           1.14.8              6f7f2dc7fab5        3 months ago        42.2 MB
k8s.gcr.io/k8s-dns-kube-dns-amd64          1.14.8              80cc5ea4b547        3 months ago        50.5 MB
k8s.gcr.io/pause-amd64                     3.1                 da86e6ba6ca1        3 months ago        742 kB
```
After I save them to tars and move them to the offline server,
I load them to my docker engine and run kubeadm init --kubernetes-version v1.10.0

**Comment by geostant** [comment]
Some logs that I've extracted from the offline system (I had to type it word by word):
```
localhost kubelet: E0408 certificate_manager.go:299] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Port https://xxx.xxx.xxx.xxx:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dail tcp xxx.xxx.xxx.xxx:6443: getsockopt: connection refused

localhost kubelet: W0408 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d

localhost kubelet: E0408 kubelet.go:2125] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

localhost kubelet: E0408 event.go:209] Unable to wrtie event: 'Post https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces/default/events: dual tcp xxx.xxx.xxx.xxx:6443: getsockopt: connection refused'
```

Obviously the main issue is port 6443 which is down
I've 2 console screens - one of the kubeadm and the second with `ss -tuna | grep -i listen` where I obviously missing 6443 in the port list.
SELINUX is disabled, firewalld is disabled and of course running as root.
The only ports that I can see up and listening (in addition to 22) are:
```
127.0.0.1:2379
127.0.0.1:10252
127.0.0.1:2380
127.0.0.1:10248
:::10250
:::10255
```

**Comment by geoffgarside** [comment]
If you run `docker ps -a` has the apiserver container ever been started?

**Comment by geostant** [comment]
@geoffgarside There is a "pasue" place holder for the api server
I got the following containers:
```
k8s.gcr.io/kube-controller-manager:v1.10.0 | k8s_kube-controller-manager
k8s.gcr.io/pause-amd:3.1 | k8s_POD_kube-controller-manager
k8s.gcr.io/pause-amd:3.1 | k8s_POD_kube-apiserver
k8s.gcr.io/pause-amd:3.1 | k8s_POD_etcd
k8s.gcr.io/pause-amd:3.1 |  k8s_POD_kube-scheduler
```

**Comment by geostant** [comment]
I'm going to try and run the same process outside on AWS on a machine that isn't connected to the internet (will connect thru VPN) to try and simulate the environment inside our isolated network

**Comment by xiangpengzhao** [comment]
~~Note that the etcd container is not running. It should run first. Is there any clue for this?~~

EDIT: just find in the issue body that you said etcd is running :) I didn't see it in https://github.com/kubernetes/kubeadm/issues/742#comment-379721844

**Comment by chuckha** [comment]
`kubeadm init` without a config will use the ip of the host's default network interface. It seems like that IP is not routing correctly to the container so the kubelet can't talk to the api server. Might be worth investigating that

**Comment by geoffgarside** [comment]
Is this the same as kubernetes/kubernetes#61277, is your etcd container crashing like @ChristianCandelaria describes?

**Comment by chuckha** [comment]
What are the specs of this machine? Plenty of resources to spare? Does it meet the minimum requirements listed here https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#before-you-begin ?

I get the exact same situation when I use a vm with .5gB of ram and when i increase it to 2gB everything works fine.

**Comment by geostant** [comment]
@geoffgarside 
Seems that ETCD doesn't even start based on the container list that I've published above
There is a "placeholser" (?) for ETCD
```k8s.gcr.io/pause-amd:3.1                   | k8s_POD_etcd```

I've noticed that on your link there is a suggestions to start ETCD seperatly
I'm going to try that.

**Comment by geostant** [comment]
@chuckha 
Plenty of resources
22 Cores (Xeon)
512G RAM
15T NVMe disks

**Comment by geoffgarside** [comment]
@geostant if you run `docker ps -a` it should show the exited containers as well, usually there will be a etcd container which has been terminated, though it looks like its been shutdown intentionally rather than crashing. I'm not sure if perhaps the livenessProbe is failing, thinking the service is dead, then restarting it. Running the etcd service externally presumably isn't using a livenessProbe. I've tried commenting out the livenessProbe but that still isn't working, so I suspect there to be some network issue somewhere that means etcd is running, but nothing can talk to the `127.0.0.1:2379` address.

**Comment by geostant** [comment]
I think that I got something... I'm trying it now
setting external yaml config file with:
```apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.10.0
etcd:
  extraArgs:
    'listen-peer-urls': '127.0.0.1:2380'

**Comment by geoffgarside** [comment]
Ah, you've got the localhost lookup/binding issue. I found that in my searching, but its not fixed my little pi cluster :( glad you've got yours working :)

**Comment by geostant** [comment]
@geoffgarside 
Not so fast - I'm waiting for several minutes to the init to finish
On ETCD logs I can see that it binds now to 127.0.0.1 and the port is not being served (`ss -tuna | grep -i listen`)

**Comment by geostant** [comment]
/var/log/messages still show connection refuse on port `6443`

**Comment by geoffgarside** [comment]
I've been trying this command to try and debug the liveness probe, I'm assuming the liveness probe is executed in the running container, and not using a separate container

``` shell
docker exec $(docker ps --format "{{.ID}}" --filter="label=io.kubernetes.container.name=etcd")   /bin/sh -ec "ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key get foo; echo \$?"
```

I'm probably just going around in circles and missing something very basic

**Comment by geostant** [comment]
apiserver container logs show:
```container_linux.go:247: starting container process caused "exec: \"kube-apiserver\": executable file not found in $PATH"```

**Comment by geoffgarside** [comment]
Thats worrying, might be worth deleting and re-pulling your api server container images down again.

**Comment by geostant** [comment]
I'm happy to inform that kubernetes cluster works great
After bypassing the localhost dns issue I had still the issue of 
```container_linux.go:247: starting container process caused "exec: \"kube-apiserver\": executable file not found in $PATH"``

which then lead to go inside the container and actually search for the command kube-apiserver which yield zero results.

Then I've searched for kube* and found kube-scheduler.
Only then I understood that on the process to bring into the isolated network the tar images I've mistakenly swapped between 2 images.

Fixed that and now I've a working cluster that runs spark 2.3.0 flawless* 

* on linux machines as with windows spark-submit fails (but that for another issue).

**Comment by kasim457** [comment]
@Geostant, how you were able bypass the local host.

I'm happy to inform that kubernetes cluster works great
After bypassing the localhost dns issue I had still the issue of
container_linux.go:247: starting container process caused "exec: \"kube-apiserver\": executable file not found in $PATH"

**Comment by kasim457** [comment]
@Geostant, how you were able bypass the local host.

I'm happy to inform that kubernetes cluster works great
After bypassing the localhost dns issue I had still the issue of
container_linux.go:247: starting container process caused "exec: \"kube-apiserver\": executable file not found in $PATH"

**Comment by kasim457** [comment]
Worker mode not able to launch weave-net and kuBe-proxy daemonsets on worker node.  Nodes tries to pull image from internet ( gcr.io). How to bypass the request. I have all images locally available and also created internal registry service as cotrainer.
